version: "3"

services:
    nextjs:
        restart: always
        build: ./
    nginx:
        restart: always
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - nextjs
