apiVersion: v1
kind: Service
metadata:
    name: nextjs
spec:
    type: LoadBalancer
    ports:
    - port: 3000 
    selector:
        app: nextjs
metadata:
    name: nginx
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: nginx
