apiVersion : apps/v1
kind: Deployment
metadata:
  name: frontend_nextjs 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend_nextjs
  template:
    metadata:
      labels:
        app: frontend_nextjs 
    spec:
      containers:
        - name: frontend_nextjs 
          image: ferndocker.azurecr.io/frontend_nextjs
          ports:
          - containerPort: 3000
