apiVersion : apps/v1
kind: Deployment
metadata:
  name: nginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend_nginx
  template:
    metadata:
      labels:
        app: frontend_nginx 
    spec:
      containers:
        - name: frontend_nginx 
          image: ferndocker.azurecr.io/frontend_nginx
          ports:
          - containerPort: 80
